[package]
name = "gorkitale"
version = "0.1.0"
edition = "2024"

[dependencies]
discord-rich-presence = "1.0.0"
tetra = "0.9.1"
rand = "0.9.2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

